### ISSUE TITLE
[Request] card-grid-course

### ISSUE THREAD

**Issue by siriwatknp** [siriwatknp/joy-treasury#37]
https://dribbble.com/shots/9323134-Web-Category-Exploration/attachments/1367507?mode=media

<img width="290" alt="image" src="https://github.com/siriwatknp/joy-treasury/assets/18292247/056addb9-6d01-4bca-8b9a-3b997d2bdd89">

**Comment by fResult** [comment]
Can I finish this issue krub?

**Comment by siriwatknp** [comment]
> Can I finish this issue krub?

Yes, please!
