### ISSUE TITLE
[Request] card-social-profile

### ISSUE THREAD

**Issue by siriwatknp** [siriwatknp/joy-treasury#57]
https://dribbble.com/shots/6384317/attachments/1367003?mode=media

<img width="299" alt="image" src="https://github.com/siriwatknp/joy-treasury/assets/18292247/09793152-74ef-40e8-b8f8-e8ac6adc6211">

**Comment by mildiemilk** [comment]
I'm on this

**Comment by mildiemilk** [comment]
I'm on this
